CANDIDATE_PROFILE = {
    "name": "Gil Ferreira Santos de Carvalho",
    "languages": {
        "french": "fluent",
        "english": "fluent",
        "portuguese": "native",
    },
    "base_country": "France",
    "target_geographies": [
        "France",
        "Portugal",
        "Switzerland",
        "Luxembourg",
        "Remote Europe",
        "Brazil",
    ],
    "primary_positioning": [
        "Treasury Manager",
        "Funding & Liquidity",
        "Treasury Transformation",
        "Structured Finance",
    ],
    "core_strength_keywords": [
        "treasury",
        "liquidity",
        "funding",
        "hedging",
        "debt structuring",
        "refinancing",
        "fx",
        "interest rate",
        "risk management",
        "dscr",
        "irr",
        "cfads",
        "project finance",
        "infrastructure finance",
        "financial modelling",
        "treasury transformation",
        "tms",
        "automation",
        "sql",
        "excel",
        "vba",
    ],
    "highest_fit_roles": [
        "Treasury Manager",
        "Treasury Front Office",
        "Funding Manager",
        "Liquidity Manager",
        "Treasury Transformation",
        "Treasury Advisory",
        "Project Finance Manager",
        "Structured Finance",
        "Infrastructure Finance",
        "Debt Advisory",
    ],
    "secondary_fit_roles": [
        "Strategic Finance",
        "Financial Risk Management",
        "Strategic FP&A",
        "Finance Transformation",
    ],
    "excluded_role_keywords": [
        "accounting",
        "audit",
        "ap",
        "ar",
        "intern",
        "graduate",
        "junior",
        "tax",
        "back office",
        "compliance",
        "pure reporting",
    ],
    "tools_keywords": [
        "bloomberg",
        "numerix",
        "titancube",
        "excel",
        "vba",
        "sql",
        "tms",
    ],
}
